### ISSUE TITLE
Try to use Paypal Onetouch

### ISSUE THREAD

**Issue by awesomedevs** [AlejandroRuiz/Braintree.Forms#1]
```
public class MainActivity : Activity, IPaymentMethodNonceCreatedListener,  IBraintreeCancelListener,  IBraintreeErrorListener
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
             SetContentView (Resource.Layout.Main);
 Button button = FindViewById<Button>(Resource.Id.myButton);
            button.Click += delegate
            {
                try
                {
                    mBraintreeFragment = BraintreeFragment.NewInstance(this, "serverURL");
                    PayPal.AuthorizeAccount(mBraintreeFragment);
                    PayPal.RequestBillingAgreement(mBraintreeFragment, new PayPalRequest());
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            };
        }
        protected BraintreeFragment mBraintreeFragment;

        public void OnError(Java.Lang.Exception p0)
        {
        }
        public void OnCancel(int p0)
        {
        }
        public void OnPaymentMethodNonceCreated(PaymentMethodNonce p0)
        {
        }
    }

```

Hello i try to use Paypal Onetouch but i have one problem if i dont add the reference Xamarin.Braintree.Android.PayPalDataCollector gives me this error:

```
FATAL EXCEPTION: main
08-04 11:39:25.709 E/AndroidRuntime(25886): java.lang.NoClassDefFoundError: com.paypal.android.sdk.data.collector.PayPalDataCollector
08-04 11:39:25.709 E/AndroidRuntime(25886): 	at com.paypal.android.sdk.onetouch.core.PayPalOneTouchCore.getClientMetadataId(PayPalOneTouchCore.java:144)
08-04 11:39:25.709 E/AndroidRuntime(25886): 	at com.paypal.android.sdk.onetouch.core.CheckoutRequest.pairingId(CheckoutRequest.java:54)
```
If i add the reference:

java.lang.IllegalArgumentException: already added :  Lcom/paypal/android/sdk/onetouch/core/metadata/MetadataIdProvider;	App1			

```
UNEXPECTED TOP-LEVEL EXCEPTION:
6>  java.lang.RuntimeException: Translation has been interrupted
6>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
6>  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
6>  	at com.android.dx.command.dexer.Main.run(Main.java:277)
6>  	at com.android.dx.command.dexer.Main.main(Main.java:245)
6>  	at com.android.dx.command.Main.main(Main.java:106)
6>  Caused by: java.lang.InterruptedException: Too many errors
6>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
6>  	... 4 more

```

Thank you in advance

**Comment by awesomedevs** [comment]
I try to enable multidex, but no success

**Comment by AlejandroRuiz** [comment]
This is still on WIP status

**Comment by tuyen-vuduc** [comment]
@awesomedevs  Have you ever looked at our repositories for Braintree.

https://github.com/NAXAM?utf8=%E2%9C%93&q=braintree&type=&language=

Cheers.
